package main

type USBRequestType uint8

const (
	USB_REQUEST_GET_STATUS        USBRequestType = 0
	USB_REQUEST_CLEAR_FEATURE     USBRequestType = 1
	USB_REQUEST_SET_FEATURE       USBRequestType = 3
	USB_REQUEST_SET_ADDRESS       USBRequestType = 5
	USB_REQUEST_GET_DESCRIPTOR    USBRequestType = 6
	USB_REQUEST_SET_DESCRIPTOR    USBRequestType = 7
	USB_REQUEST_GET_CONFIGURATION USBRequestType = 8
	USB_REQUEST_SET_CONFIGURATION USBRequestType = 9
	USB_REQUEST_GET_INTERFACE     USBRequestType = 10
	USB_REQUEST_SET_INTERFACE     USBRequestType = 11
	USB_REQUEST_SYNCH_FRAME       USBRequestType = 12
)

var deviceRequestDescriptons = map[USBRequestType]string{
	USB_REQUEST_GET_STATUS:        "USB_REQUEST_GET_STATUS",
	USB_REQUEST_CLEAR_FEATURE:     "USB_REQUEST_CLEAR_FEATURE",
	USB_REQUEST_SET_FEATURE:       "USB_REQUEST_SET_FEATURE",
	USB_REQUEST_SET_ADDRESS:       "USB_REQUEST_SET_ADDRESS",
	USB_REQUEST_GET_DESCRIPTOR:    "USB_REQUEST_GET_DESCRIPTOR",
	USB_REQUEST_SET_DESCRIPTOR:    "USB_REQUEST_SET_DESCRIPTOR",
	USB_REQUEST_GET_CONFIGURATION: "USB_REQUEST_GET_CONFIGURATION",
	USB_REQUEST_SET_CONFIGURATION: "USB_REQUEST_SET_CONFIGURATION",
	USB_REQUEST_GET_INTERFACE:     "USB_REQUEST_GET_INTERFACE",
	USB_REQUEST_SET_INTERFACE:     "USB_REQUEST_SET_INTERFACE",
	USB_REQUEST_SYNCH_FRAME:       "USB_REQUEST_SYNCH_FRAME",
}

type USBDescriptorType uint8

const (
	USB_DESCRIPTOR_DEVICE                    USBDescriptorType = 1
	USB_DESCRIPTOR_CONFIGURATION             USBDescriptorType = 2
	USB_DESCRIPTOR_STRING                    USBDescriptorType = 3
	USB_DESCRIPTOR_INTERFACE                 USBDescriptorType = 4
	USB_DESCRIPTOR_ENDPOINT                  USBDescriptorType = 5
	USB_DESCRIPTOR_DEVICE_QUALIFIER          USBDescriptorType = 6
	USB_DESCRIPTOR_OTHER_SPEED_CONFIGURATION USBDescriptorType = 7
	USB_DESCRIPTOR_INTERFACE_POWER           USBDescriptorType = 8
	USB_DESCRIPTOR_HID                       USBDescriptorType = 33
	USB_DESCRIPTOR_HID_REPORT                USBDescriptorType = 34
)

type USBHIDRequestType uint8

const (
	USB_HID_REQUEST_GET_REPORT   USBHIDRequestType = 1
	USB_HID_REQUEST_GET_IDLE     USBHIDRequestType = 2
	USB_HID_REQUEST_GET_PROTOCOL USBHIDRequestType = 3
	USB_HID_REQUEST_SET_REPORT   USBHIDRequestType = 9
	USB_HID_REQUEST_SET_IDLE     USBHIDRequestType = 10
	USB_HID_REQUEST_SET_PROTOCOL USBHIDRequestType = 11
)

var interfaceRequestDescriptions = map[USBHIDRequestType]string{
	USB_HID_REQUEST_GET_REPORT:   "USB_HID_REQUEST_GET_REPORT",
	USB_HID_REQUEST_GET_IDLE:     "USB_HID_REQUEST_GET_IDLE",
	USB_HID_REQUEST_GET_PROTOCOL: "USB_HID_REQUEST_GET_PROTOCOL",
	USB_HID_REQUEST_SET_REPORT:   "USB_HID_REQUEST_SET_REPORT",
	USB_HID_REQUEST_SET_IDLE:     "USB_HID_REQUEST_SET_IDLE",
	USB_HID_REQUEST_SET_PROTOCOL: "USB_HID_REQUEST_SET_PROTOCOL",
}

type USBDirection uint8

const (
	USB_HOST_TO_DEVICE USBDirection = 0
	USB_DEVICE_TO_HOST USBDirection = 1
)

var requestDirectionDescriptions = map[USBDirection]string{
	USB_HOST_TO_DEVICE: "USB_HOST_TO_DEVICE",
	USB_DEVICE_TO_HOST: "USB_DEVICE_TO_HOST",
}

type USBRequestClass uint8

const (
	USB_REQUEST_CLASS_STANDARD USBRequestClass = 0
	USB_REQUEST_CLASS_CLASS    USBRequestClass = 1
	USB_REQUEST_CLASS_VENDOR   USBRequestClass = 2
	USB_REQUEST_CLASS_RESERVED USBRequestClass = 3
)

var requestClassDescriptons = map[USBRequestClass]string{
	USB_REQUEST_CLASS_STANDARD: "USB_REQUEST_CLASS_STANDARD",
	USB_REQUEST_CLASS_CLASS:    "USB_REQUEST_CLASS_CLASS",
	USB_REQUEST_CLASS_VENDOR:   "USB_REQUEST_CLASS_VENDOR",
	USB_REQUEST_CLASS_RESERVED: "USB_REQUEST_CLASS_RESERVED",
}

type USBRequestRecipient uint8

const (
	USB_REQUEST_RECIPIENT_DEVICE    USBRequestRecipient = 0
	USB_REQUEST_RECIPIENT_INTERFACE USBRequestRecipient = 1
	USB_REQUEST_RECIPIENT_ENDPOINT  USBRequestRecipient = 2
	USB_REQUEST_RECIPIENT_OTHER     USBRequestRecipient = 3
)

var requestRecipientDescriptions = map[USBRequestRecipient]string{
	USB_REQUEST_RECIPIENT_DEVICE:    "USB_REQUEST_RECIPIENT_DEVICE",
	USB_REQUEST_RECIPIENT_INTERFACE: "USB_REQUEST_RECIPIENT_INTERFACE",
	USB_REQUEST_RECIPIENT_ENDPOINT:  "USB_REQUEST_RECIPIENT_ENDPOINT",
	USB_REQUEST_RECIPIENT_OTHER:     "USB_REQUEST_RECIPIENT_OTHER",
}

const (
	USB_CONFIG_ATTR_BASE          = 0b10000000
	USB_CONFIG_ATTR_SELF_POWERED  = 0b01000000
	USB_CONFIG_ATTR_REMOTE_WAKEUP = 0b00100000

	USB_INTERFACE_CLASS_HID = 3
)
